# Generated by Django 3.2.6 on 2021-12-29 18:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_you', tinymce.models.HTMLField()),
                ('email', models.EmailField(max_length=254)),
                ('Date_of_Birth', models.DateField()),
                ('Phone', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=200)),
                ('skills1', models.CharField(max_length=200)),
                ('skills2', models.CharField(max_length=200)),
                ('skills3', models.CharField(max_length=200)),
                ('skills4', models.CharField(max_length=200)),
                ('desc', tinymce.models.HTMLField()),
                ('your_image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_No', models.IntegerField()),
                ('skills_title', models.CharField(max_length=50)),
                ('konwledge_percentage', models.IntegerField()),
            ],
        ),
    ]
