# Generated by Django 3.2.6 on 2021-12-29 18:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_desc', tinymce.models.HTMLField()),
                ('strt_year1', models.CharField(max_length=4)),
                ('end_year1', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_title', models.CharField(max_length=500)),
                ('strt_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('exp_desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='Resume',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='skills3',
            field=models.CharField(default='.........', max_length=200),
        ),
    ]
