# Generated by Django 3.2.6 on 2021-12-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211230_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('icon1', 'fa fa-mobile-alt'), ('icon2', 'fa fa-bullhorn'), ('icon3', 'fa fa-search'), ('icon4', 'fa fa-code'), ('icon5', 'fa fa-palette'), ('icon6', 'fa fa-laptop-code')], max_length=50)),
                ('service_title', models.CharField(max_length=100)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
