# Generated by Django 3.2.6 on 2021-12-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
    ]
