# Generated by Django 3.2.6 on 2021-12-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_services_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('icon1', 'fa fa-mobile-alt'), ('icon2', 'fa fa-bullhorn'), ('icon3', 'fa fa-search'), ('icon4', 'fa fa-code'), ('icon5', 'fa fa-palette'), ('icon6', 'fa fa-laptop-code')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
