# Generated by Django 3.2.6 on 2021-12-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('fa fa-mobile-alt', 'mobile_icon'), ('fa fa-bullhorn', 'icon2'), ('fa fa-search', 'search_icon'), ('fa fa-code', 'code_icon'), ('fa fa-palette', 'icon4'), ('fa fa-laptop-code', 'icon5')], max_length=50),
        ),
    ]
