# Generated by Django 3.2.6 on 2021-12-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=10)),
                ('website_name', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=100)),
            ],
        ),
    ]
