# Generated by Django 3.2.6 on 2021-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='links',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='Date_of_Birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Degree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='skills1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='skills2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='skills3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='skills4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
