# Generated by Django 3.2.6 on 2021-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211230_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='city',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_you',
        ),
        migrations.AddField(
            model_name='about',
            name='Awards',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='Clients',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='Experience',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='First_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='Projects',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='Second_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='display_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
