# Generated by Django 3.2.6 on 2021-12-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211231_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='konwledge_percentage',
            field=models.IntegerField(blank=True),
        ),
    ]
