# Generated by Django 3.2.6 on 2021-12-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211231_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
