# Generated by Django 3.2.6 on 2021-12-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211231_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='some_text',
            field=models.TextField(blank=True),
        ),
    ]
