# Generated by Django 3.2.6 on 2022-02-12 13:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contact_some_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('author_name', models.CharField(default='unknown', max_length=100)),
                ('feature_image', models.ImageField(upload_to='media')),
                ('desc', tinymce.models.HTMLField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
