# Generated by Django 3.2.6 on 2022-02-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
